# Generated by Django 4.1 on 2022-11-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pyerkdjango", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("uri", models.TextField(default="(unknown uri)")),
                ("description", models.TextField(default="", null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LanguageSpecifiedString",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("langtag", models.CharField(default="", max_length=8)),
                ("content", models.TextField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.AddField(
            model_name="entity",
            name="label",
            field=models.ManyToManyField(to="pyerkdjango.languagespecifiedstring"),
        ),
    ]
